import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import Parser from 'rss-parser';

const parser = new Parser();

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json());

  // Google Verification & Robots
  app.get('/google8cbb8882481f698b.html', (req, res) => {
    res.type('text/html');
    res.send('google-site-verification: google8cbb8882481f698b.html');
  });

  app.get('/robots.txt', (req, res) => {
    res.type('text/plain');
    res.send('User-agent: *\nAllow: /\n\nSitemap: https://opportunityhubsa.co.za/sitemap.xml');
  });

  app.get('/sitemap.xml', (req, res) => {
    res.header('Content-Type', 'application/xml');
    res.sendFile(path.join(process.cwd(), 'sitemap.xml'));
  });

  // API Routes
  app.get("/api/news/fetch", async (req, res) => {
    try {
      const results: any[] = [];
      
      // 1. Fetch from SA News RSS
      try {
        const feed = await parser.parseURL('https://www.sanews.gov.za/rss.xml');
        feed.items.slice(0, 5).forEach(item => {
          results.push({
            title: item.title,
            summary: item.contentSnippet || item.content,
            content: item.content || item.contentSnippet,
            url: item.link,
            source: 'SA News',
            category: 'Government/Employment',
            imageUrl: 'https://www.sanews.gov.za/sites/all/themes/sanews/logo.png',
            status: 'draft',
            isAutoGenerated: true
          });
        });
      } catch (err) {
        console.error('RSS Fetch fail:', err);
      }

      // 2. Fetch from NewsData.io (if API key provided)
      const newsDataKey = process.env.NEWSDATA_API_KEY;
      if (newsDataKey) {
        try {
          const response = await fetch(`https://newsdata.io/api/1/news?apikey=${newsDataKey}&q=career%20jobs%20south%20africa&country=za&language=en`);
          const data = await response.json();
          if (response.ok && Array.isArray(data.results)) {
            data.results.slice(0, 5).forEach((item: any) => {
              results.push({
                title: item.title,
                summary: item.description,
                content: item.content || item.description,
                url: item.link,
                source: item.source_id || 'NewsData.io',
                category: 'Market Trends',
                imageUrl: item.image_url || 'https://images.unsplash.com/photo-1504711432869-efd597cdd045?auto=format&fit=crop&q=80',
                status: 'draft',
                isAutoGenerated: true
              });
            });
          }
        } catch (err) {
          console.error('NewsData fetch fail:', err);
        }
      }

      res.json(results);
    } catch (error) {
      res.status(500).json({ error: 'Failed to fetch news' });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
