import React from 'react';
import { 
  ArrowLeft, 
  Newspaper, 
  PlusCircle, 
  Bold, 
  Italic, 
  List, 
  Link as LinkIcon,
  Globe,
  Image as ImageIcon,
  Save
} from 'lucide-react';
import { motion } from 'motion/react';
import { 
  collection, 
  addDoc, 
  updateDoc, 
  doc, 
  getDoc, 
  serverTimestamp 
} from 'firebase/firestore';
import { db, auth } from '../../lib/firebase';

interface AdminNewsFormProps {
  newsId?: string | null;
  onSuccess: () => void;
  onCancel: () => void;
}

export default function AdminNewsForm({ newsId, onSuccess, onCancel }: AdminNewsFormProps) {
  const [isSubmitting, setIsSubmitting] = React.useState(false);
  const [loading, setLoading] = React.useState(!!newsId);
  const [formData, setFormData] = React.useState({
    title: '',
    summary: '',
    content: '',
    source: '',
    url: '',
    imageUrl: '',
    category: 'Careers',
    status: 'draft',
    isHeroBanner: false
  });

  React.useEffect(() => {
    if (newsId) {
      const fetchNews = async () => {
        try {
          const docRef = doc(db, 'news', newsId);
          const docSnap = await getDoc(docRef);
            if (docSnap.exists()) {
              setFormData(prev => ({ ...prev, ...docSnap.data() }));
            }
        } catch (error) {
          console.error('Error fetching news:', error);
        } finally {
          setLoading(false);
        }
      };
      fetchNews();
    }
  }, [newsId]);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value, type } = e.target as any;
    const val = type === 'checkbox' ? (e.target as HTMLInputElement).checked : value;
    setFormData(prev => ({ ...prev, [name]: val }));
  };

  const handleSubmit = async (status: 'draft' | 'published') => {
    const user = auth.currentUser;
    if (!user) return;

    setIsSubmitting(true);
    
    const timeoutId = setTimeout(() => {
      if (isSubmitting) {
        setIsSubmitting(false);
        // We can't use setSubmitStatus as it's not and defined in the component state, but let's check
      }
    }, 15000);

    const payload = {
      ...formData,
      status,
      authorId: user.uid,
      updatedAt: serverTimestamp(),
      isAutoGenerated: false
    };
    
    try {
      if (newsId) {
        await updateDoc(doc(db, 'news', newsId), payload);
      } else {
        await addDoc(collection(db, 'news'), {
          ...payload,
          createdAt: serverTimestamp()
        });
      }
      clearTimeout(timeoutId);
      onSuccess();
    } catch (error: any) {
      clearTimeout(timeoutId);
      console.error('Save failed:', error);
      alert(`Save failed: ${error.message}`);
    } finally {
      setIsSubmitting(false);
    }
  };

  if (loading) return <div>Loading...</div>;

  return (
    <div className="max-w-4xl mx-auto space-y-8 pb-20">
      <div className="flex items-center justify-between group">
        <button onClick={onCancel} className="flex items-center space-x-2 text-slate-500 hover:text-slate-900 transition-colors">
          <ArrowLeft className="w-5 h-5 group-hover:-translate-x-1 transition-transform" />
          <span className="font-bold">Back to Trends</span>
        </button>
        <div className="flex space-x-3">
          <button 
            onClick={() => handleSubmit('draft')}
            className="px-6 py-2 border border-slate-200 rounded-xl text-sm font-bold hover:bg-slate-100 transition-all"
          >
            Save Draft
          </button>
          <button 
            onClick={() => handleSubmit('published')}
            disabled={isSubmitting}
            className="bg-emerald-500 text-white px-6 py-2 rounded-xl text-sm font-bold hover:bg-emerald-600 shadow-lg shadow-emerald-100 disabled:opacity-50 flex items-center space-x-2"
          >
            {isSubmitting ? (
              <>
                <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                <span>Working...</span>
              </>
            ) : (
              <span>{newsId ? 'Update & Publish' : 'Publish Trend'}</span>
            )}
          </button>
        </div>
      </div>

      <div className="bg-white rounded-3xl border border-slate-200 p-8 shadow-sm space-y-8">
        <section className="space-y-6">
          <div className="flex items-center space-x-3 text-slate-900 pb-4 border-b border-slate-50">
            <PlusCircle className="w-5 h-5 text-emerald-500" />
            <h2 className="font-bold">Trend Content</h2>
          </div>
          
          <div className="space-y-4">
            <div className="flex items-center space-x-3 p-4 bg-emerald-50 rounded-xl border border-emerald-100">
              <input
                type="checkbox"
                id="isHeroBanner"
                name="isHeroBanner"
                checked={formData.isHeroBanner}
                onChange={handleInputChange}
                className="w-5 h-5 rounded text-emerald-500 focus:ring-emerald-500"
              />
              <label htmlFor="isHeroBanner" className="text-sm font-bold text-emerald-700">
                Show as Top Announcement Bar on Home Page
              </label>
            </div>

            <div>
              <label className="block text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-2">Headline</label>
              <input
                type="text"
                name="title"
                value={formData.title}
                onChange={handleInputChange}
                className="w-full bg-slate-50 border border-slate-100 rounded-xl px-4 py-3 focus:outline-none focus:ring-2 focus:ring-emerald-500/20"
                placeholder="e.g. New Careers in Renewable Energy"
              />
            </div>

            <div>
              <label className="block text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-2">Short Summary</label>
              <textarea
                name="summary"
                value={formData.summary}
                onChange={handleInputChange}
                rows={2}
                className="w-full bg-slate-50 border border-slate-100 rounded-xl px-4 py-3 focus:outline-none resize-none"
                placeholder="Brief intro for the news listing..."
              />
            </div>

            <div>
              <label className="block text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-2">Full Content</label>
              <textarea
                name="content"
                value={formData.content}
                onChange={handleInputChange}
                rows={10}
                className="w-full bg-slate-50 border border-slate-100 rounded-xl px-4 py-3 focus:outline-none"
                placeholder="Write the full news story here..."
              />
            </div>
          </div>
        </section>

        <section className="space-y-6">
          <div className="flex items-center space-x-3 text-slate-900 pb-4 border-b border-slate-50">
            <Globe className="w-5 h-5 text-emerald-500" />
            <h2 className="font-bold">Source & Media</h2>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <label className="block text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-2">Origin/Source</label>
              <input
                type="text"
                name="source"
                value={formData.source}
                onChange={handleInputChange}
                className="w-full bg-slate-50 border border-slate-100 rounded-xl px-4 py-3 focus:outline-none"
                placeholder="e.g. SA News Service"
              />
            </div>
            <div>
              <label className="block text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-2">Original URL</label>
              <input
                type="text"
                name="url"
                value={formData.url}
                onChange={handleInputChange}
                className="w-full bg-slate-50 border border-slate-100 rounded-xl px-4 py-3 focus:outline-none"
                placeholder="Link to source article"
              />
            </div>
          </div>

          <div>
            <label className="block text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-2">Featured Image URL</label>
            <div className="flex space-x-4">
              <div className="flex-1">
                <input
                  type="text"
                  name="imageUrl"
                  value={formData.imageUrl}
                  onChange={handleInputChange}
                  className="w-full bg-slate-50 border border-slate-100 rounded-xl px-4 py-3 focus:outline-none"
                  placeholder="https://images.unsplash.com/..."
                />
              </div>
              {formData.imageUrl && (
                <div className="w-12 h-12 rounded-xl overflow-hidden border border-slate-200">
                  <img src={formData.imageUrl} alt="Preview" className="w-full h-full object-cover" />
                </div>
              )}
            </div>
          </div>
        </section>

        <div className="flex justify-end pt-8">
          <button 
            onClick={() => handleSubmit('published')}
            disabled={isSubmitting}
            className="px-12 py-4 bg-slate-900 text-white rounded-2xl font-bold hover:bg-slate-800 transition-all shadow-xl shadow-slate-200 flex items-center space-x-2"
          >
            <Save className="w-5 h-5" />
            <span>Save Trend Article</span>
          </button>
        </div>
      </div>
    </div>
  );
}
