import React from 'react';
import { 
  collection, 
  query, 
  onSnapshot, 
  orderBy, 
  deleteDoc, 
  doc 
} from 'firebase/firestore';
import { db } from '../../lib/firebase';
import { 
  Edit3, 
  Trash2, 
  ChevronLeft, 
  ChevronRight, 
  Newspaper,
  Globe,
  Plus,
  RefreshCw
} from 'lucide-react';

interface NewsItem {
  id: string;
  title: string;
  summary: string;
  source: string;
  status: 'draft' | 'published';
  createdAt: any;
  isAutoGenerated?: boolean;
}

interface AdminNewsProps {
  onEdit: (id: string) => void;
  onNew: () => void;
  onAutoFetch: () => void;
}

export default function AdminNews({ onEdit, onNew, onAutoFetch }: AdminNewsProps) {
  const [news, setNews] = React.useState<NewsItem[]>([]);
  const [loading, setLoading] = React.useState(true);
  const [activeFilter, setActiveFilter] = React.useState('all');

  React.useEffect(() => {
    const q = query(collection(db, 'news'), orderBy('createdAt', 'desc'));
    const unsubscribe = onSnapshot(q, (snapshot) => {
      const data = snapshot.docs.map(doc => ({
        id: doc.id,
        ...doc.data()
      })) as NewsItem[];
      setNews(data);
      setLoading(false);
    });
    return () => unsubscribe();
  }, []);

  const handleDelete = async (id: string) => {
    if (window.confirm('Are you sure you want to delete this news item?')) {
      try {
        await deleteDoc(doc(db, 'news', id));
      } catch (error) {
        console.error('Error deleting:', error);
      }
    }
  };

  const filtered = news.filter(item => {
    if (activeFilter === 'all') return true;
    return item.status === activeFilter;
  });

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div className="flex bg-slate-100 p-1 rounded-xl">
          {['all', 'published', 'draft'].map((filter) => (
            <button
              key={filter}
              onClick={() => setActiveFilter(filter)}
              className={`px-4 py-1.5 rounded-lg text-sm font-medium capitalize transition-all ${
                activeFilter === filter
                  ? 'bg-slate-900 text-white shadow-sm'
                  : 'text-slate-600 hover:text-slate-900'
              }`}
            >
              {filter} ({news.filter(o => filter === 'all' || o.status === filter).length})
            </button>
          ))}
        </div>

        <div className="flex space-x-3">
          <button 
            onClick={onAutoFetch}
            className="bg-emerald-50 text-emerald-600 border border-emerald-100 px-4 py-2 rounded-xl font-bold flex items-center space-x-2 hover:bg-emerald-100 transition-colors"
          >
            <RefreshCw className="w-5 h-5" />
            <span>Fetch AI Trend</span>
          </button>
          <button 
            onClick={onNew}
            className="bg-slate-900 text-white px-4 py-2 rounded-xl font-bold flex items-center space-x-2 hover:bg-slate-800 transition-colors shadow-lg shadow-slate-200"
          >
            <Plus className="w-5 h-5" />
            <span>Post Trend Manually</span>
          </button>
        </div>
      </div>

      <div className="bg-white border border-slate-200 rounded-3xl overflow-hidden shadow-sm">
        <div className="overflow-x-auto">
          <table className="w-full text-left">
            <thead className="bg-slate-50 border-b border-slate-200">
              <tr>
                <th className="px-6 py-4 text-[10px] font-bold text-slate-400 uppercase tracking-widest">Headline</th>
                <th className="px-6 py-4 text-[10px] font-bold text-slate-400 uppercase tracking-widest">Source</th>
                <th className="px-6 py-4 text-[10px] font-bold text-slate-400 uppercase tracking-widest">Type</th>
                <th className="px-6 py-4 text-[10px] font-bold text-slate-400 uppercase tracking-widest">Status</th>
                <th className="px-6 py-4 text-[10px] font-bold text-slate-400 uppercase tracking-widest text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {filtered.map((item) => (
                <tr key={item.id} className="hover:bg-slate-50/50 transition-colors group">
                  <td className="px-6 py-4 max-w-md">
                    <div className="flex items-center space-x-4">
                      <div className={`w-10 h-10 ${item.isAutoGenerated ? 'bg-emerald-100' : 'bg-slate-100'} rounded-xl flex items-center justify-center p-2 group-hover:bg-white transition-colors`}>
                        <Newspaper className={`w-5 h-5 ${item.isAutoGenerated ? 'text-emerald-500' : 'text-slate-500'}`} />
                      </div>
                      <div>
                        <p className="text-sm font-bold text-slate-900 group-hover:text-emerald-600 transition-colors line-clamp-1">{item.title}</p>
                        <p className="text-xs text-slate-500 line-clamp-1">{item.summary}</p>
                      </div>
                    </div>
                  </td>
                  <td className="px-6 py-4">
                    <div className="flex items-center space-x-2 text-slate-600">
                      <Globe className="w-4 h-4" />
                      <span className="text-xs font-medium">{item.source || 'Manual Post'}</span>
                    </div>
                  </td>
                  <td className="px-6 py-4">
                    <span className={`px-3 py-1 rounded-full text-[10px] font-bold uppercase ${
                      item.isAutoGenerated ? 'bg-emerald-100 text-emerald-700' : 'bg-blue-100 text-blue-700'
                    }`}>
                      {item.isAutoGenerated ? 'AI Fetched' : 'Manual'}
                    </span>
                  </td>
                  <td className="px-6 py-4">
                    <div className="flex items-center space-x-2">
                      <div className={`w-2 h-2 rounded-full ${item.status === 'published' ? 'bg-emerald-500' : 'bg-slate-300'}`}></div>
                      <span className="text-xs font-medium text-slate-600 capitalize">{item.status}</span>
                    </div>
                  </td>
                  <td className="px-6 py-4">
                    <div className="flex items-center justify-end space-x-2">
                      <button 
                        onClick={() => onEdit(item.id)}
                        className="p-2 text-slate-400 hover:text-emerald-500 transition-colors"
                      >
                        <Edit3 className="w-4 h-4" />
                      </button>
                      <button 
                        onClick={() => handleDelete(item.id)}
                        className="p-2 text-slate-400 hover:text-red-500 transition-colors"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        
        {filtered.length === 0 && !loading && (
          <div className="p-12 text-center">
            <div className="w-16 h-16 bg-slate-50 rounded-full flex items-center justify-center mx-auto mb-4 border border-slate-100">
              <Newspaper className="w-8 h-8 text-slate-300" />
            </div>
            <p className="text-slate-500 font-medium">No trend items found.</p>
          </div>
        )}

        <div className="px-6 py-4 bg-slate-50 border-t border-slate-200 flex items-center justify-between">
          <p className="text-xs text-slate-500 font-medium">
            Showing <span className="text-slate-900">1 to {filtered.length}</span> of <span className="text-slate-900">{filtered.length}</span> results
          </p>
          
          <div className="flex items-center space-x-2">
            <button className="p-2 border border-slate-200 rounded-lg text-slate-400 hover:bg-white hover:text-slate-900 transition-all disabled:opacity-50">
              <ChevronLeft className="w-4 h-4" />
            </button>
            <button className="p-2 border border-slate-200 rounded-lg text-slate-400 hover:bg-white hover:text-slate-900 transition-all disabled:opacity-50">
              <ChevronRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
